[package]
name = "isent_it"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
bevy = "0.14.2"
bevy_editor_pls = "0.10.0"
bevy_magic_light_2d = "0.8.1"

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3

[profile.release]
opt-level = 'z'
