FROM rust:latest AS rs
WORKDIR /app

COPY . .

RUN rustup target add wasm32-unknown-unknown && cargo install -f wasm-bindgen-cli --version 0.2.97

RUN cargo build --release --bin client --target wasm32-unknown-unknown
RUN cargo install wasm-opt && wasm-opt -Os -o ./client.wasm ./target/wasm32-unknown-unknown/release/client.wasm
RUN wasm-bindgen --out-dir ./out --target web ./client.wasm

FROM rust:latest AS rss
WORKDIR /app

RUN git clone https://github.com/Loshido/rust_static_server /app
RUN rustup target add aarch64-unknown-linux-musl
RUN cargo build --release --target aarch64-unknown-linux-musl

FROM alpine:latest AS prod
WORKDIR /app

COPY --from=rss /app/target/aarch64-unknown-linux-musl/release/static_server /bin/static_server
COPY ./assets /app/assets
COPY ./web /app/
COPY --from=rs /app/out /app/js

ENV ROCKET_ADDRESS="0.0.0.0"
ENV ROCKET_PORT="80"
EXPOSE 80
# Rust static server binary
CMD [ "/bin/static_server" ]