FROM rust:latest AS rss
WORKDIR /app

RUN git clone https://github.com/Loshido/rust_static_server /app
RUN rustup target add aarch64-unknown-linux-musl
ENV TARGET_CC=/usr/bin/clang
RUN cargo build --release --target aarch64-unknown-linux-musl

FROM alpine:latest AS prod
WORKDIR /app

COPY --from=rss /app/target/aarch64-unknown-linux-musl/release/static_server /bin/static_server
COPY ./assets /app/assets
COPY ./web /app/
COPY ./actions/js /app/js

ENV ROCKET_ADDRESS="0.0.0.0"
ENV ROCKET_PORT="80"
EXPOSE 80
# Rust static server binary
CMD [ "/bin/static_server" ]