FROM rust:latest AS rs
WORKDIR /bevy

COPY . .

ENV TARGET_CC=/usr/bin/clang
RUN cargo build --release --bin server

FROM debian:trixie-slim AS prod
WORKDIR /app

COPY --from=rs /bevy/target/release/server /app/server

ENV PORT=25565
EXPOSE 25565
CMD [ "/app/server" ]