name: Build and Push Isen't it to Docker Hub

# RUSTFLAGS=

on:
  push:
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]

env:
  RUSTFLAGS: --cfg=web_sys_unstable_apis

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        target: wasm32-unknown-unknown
        override: true

    - name: Install wasm-bindgen-cli
      run: |
        cargo install wasm-bindgen-cli

    - name: Build Rust app for wasm32 target
      run: |
        cargo build --release --target wasm32-unknown-unknown --bin client

    - name: Prepare wasm output
      run: |
        wasm-bindgen --out-dir ./actions/js --target web target/wasm32-unknown-unknown/release/client.wasm

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.web
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/isent_it:latest
