name: Build and Push "Isen't it" server to Docker Hub

# RUSTFLAGS=

on:
  push:
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: aarch64-unknown-linux-musl
        override: true

    - name: Install Bevy's dependencies
      run: apt-get update && \
        apt-get install g++ pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0

    - name: Cache
      uses: Swatinem/rust-cache@v2

    - name: Build arm64 for alpine
      uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --release --target=aarch64-unknown-linux-musl --bin server

    - name: Prepare binaries
      run: |
        mv target/aarch64-unknown-linux-musl/release/server  /app/listen

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.server
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/isent_it_server:latest
